name: sphinxtest
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - alabaster=0.7.12=py_0
  - babel=2.8.0=py_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38he774522_1000
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.14.3=py38h7a1dbc1_0
  - chardet=3.0.4=py38_1003
  - cryptography=3.1.1=py38h7a1dbc1_0
  - cudatoolkit=10.2.89=h74a9793_1
  - docutils=0.16=py38_1
  - freetype=2.10.4=hd328e21_0
  - idna=2.10=py_0
  - imagesize=1.2.0=py_0
  - intel-openmp=2020.2=254
  - jinja2=2.11.2=py_0
  - jpeg=9b=hb83a4c4_2
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.1.0=h56a325e_1
  - libuv=1.40.0=he774522_0
  - lz4-c=1.9.2=hf4a77e7_3
  - markupsafe=1.1.1=py38he774522_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38hb782905_0
  - mkl_fft=1.2.0=py38h45dec08_0
  - mkl_random=1.1.1=py38h47e9c7a_0
  - ninja=1.10.1=py38h7ef1ec2_0
  - numpy-base=1.19.2=py38ha3acd2a_0
  - olefile=0.46=py_0
  - openssl=1.1.1h=he774522_0
  - packaging=20.4=py_0
  - pillow=8.0.1=py38h4fa10fc_0
  - pip=20.2.4=py38_0
  - pycparser=2.20=py_2
  - pygments=2.7.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pysocks=1.7.1=py38_0
  - python=3.8.5=h5fd99cc_1
  - pytorch=1.7.0=py3.8_cuda102_cudnn7_0
  - pytz=2020.1=py_0
  - requests=2.24.0=py_0
  - setuptools=50.3.0=py38h9490d1a_1
  - six=1.15.0=py_0
  - snowballstemmer=2.0.0=py_0
  - sphinx=3.2.1=py_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sqlite=3.33.0=h2a8f88b_0
  - tk=8.6.10=he774522_0
  - torchaudio=0.7.0=py38
  - torchvision=0.8.1=py38_cu102
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.25.11=py_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wheel=0.35.1=py_0
  - win_inet_pton=1.1.0=py38_0
  - wincertstore=0.2=py38_0
  - xz=5.2.5=h62dcd97_0
  - zlib=1.2.11=vc14h1cdd9ab_1
  - zstd=1.4.5=h04227a9_0
  - pip:
    - cloudpickle==1.6.0
    - colorama==0.4.4
    - cycler==0.10.0
    - dataclasses==0.6
    - future==0.18.2
    - gym==0.17.3
    - joblib==0.17.0
    - kiwisolver==1.3.1
    - matplotlib==3.3.2
    - numpy==1.19.4
    - progressbar==2.5
    - pyglet==1.5.0
    - python-dateutil==2.8.1
    - pyyaml==5.3.1
    - scikit-learn==0.23.2
    - scipy==1.5.4
    - sphinx-rtd-theme==0.5.0
    - threadpoolctl==2.1.0
    - tqdm==4.51.0
prefix: C:\ProgramData\Anaconda3\envs\sphinxtest
